version: "3"

services:
  db:
    image: pgvector/pgvector:0.8.0-pg17
    command: [ ]
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5438:5432"
    volumes:
      - db-data:/var/lib/postgresql/default_code

volumes:
  db-data: