[versions]
kotlin = "2.4.10"
exposed = "1.5.0"
quati-util = "2.4.0"
kotlinx-coroutine = "1.11.0"
kotlinx-serialization = "1.11.0"
jdbc-postgresql = "42.7.13"
r2dbc-postgresql = "1.1.2.RELEASE"
r2dbc-pool = "1.0.2.RELEASE"

[libraries]
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-crypt = { module = "org.jetbrains.exposed:exposed-crypt", version.ref = "exposed" }
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed" }
exposed-json = { module = "org.jetbrains.exposed:exposed-json", version.ref = "exposed" }
exposed-datetime = { module = "org.jetbrains.exposed:exposed-kotlin-datetime", version.ref = "exposed" }

exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
jdbc-postgresql = { module = "org.postgresql:postgresql", version.ref = "jdbc-postgresql" }

exposed-r2dbc = { module = "org.jetbrains.exposed:exposed-r2dbc", version.ref = "exposed" }
r2dbc-postgresql = { module = "org.postgresql:r2dbc-postgresql", version.ref = "r2dbc-postgresql" }
r2dbc-pool = { module = "io.r2dbc:r2dbc-pool", version.ref = "r2dbc-pool" }

goquati-base = { module = "de.quati:kotlin-util", version.ref = "quati-util" }

ipaddress = { module = "com.github.seancfoley:ipaddress", version = "5.5.1" }

kotlinx-coroutine-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutine" }
kotlinx-coroutine-reactor = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactor", version.ref = "kotlinx-coroutine" }

kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core-jvm", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json-jvm", version.ref = "kotlinx-serialization" }

[bundles]
exposed = [
    "exposed-core",
    "exposed-crypt",
    "exposed-dao",
    "exposed-json",
    "exposed-datetime",
]
exposed-jdbc = [
    "exposed-jdbc",
    "jdbc-postgresql",
]
exposed-r2dbc = [
    "exposed-r2dbc",
    "r2dbc-postgresql",
    "r2dbc-pool",
]
kotlinx-coroutine = [
    "kotlinx-coroutine-core",
    "kotlinx-coroutine-reactor",
]
kotlinx-serialization = [
    "kotlinx-serialization-core",
    "kotlinx-serialization-json",
]

[plugins]
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
